package com.example.functionalprototype;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;


public class ReportFeature extends AppCompatActivity
implements AdapterView.OnItemSelectedListener, View.OnClickListener {

    // Dropdown: Report an issue with the app or study space/bathroom
    private Spinner reportDropdownAnswer;
    private Button nextButton;

    private Button backButton;

    private Button homeButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // These were generated by AndroidStudio
        // I deleted any other auto-generated pieces that
        // were not used in Lecture 10/20
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_report_feature);

        // Grab our spinner (dropdown) submission
        reportDropdownAnswer = (Spinner) findViewById(R.id.reporting_type_dropdown);

        // Respond to user selecting a dropdown choice
        // DOCS: https://developer.android.com/reference/android/widget/AdapterView.OnItemSelectedListener
        reportDropdownAnswer.setOnItemSelectedListener(this);

        // Added by Stella
        Button menuButton = findViewById(R.id.menu_button);
        menuButton.setOnClickListener(v -> {
            Intent intent = new Intent(ReportFeature.this, Menu.class);
            startActivity(intent);
        });

        // The user has pressed the 'Next' Button
        nextButton = (Button) findViewById(R.id.next_button_report_feature);
        nextButton.setOnClickListener(this);

        // The user has pressed the 'Back' Button
        backButton = (Button) findViewById(R.id.back_button_report_feature);
        backButton.setOnClickListener(this);

        // The user has pressed the 'Home' Button
        homeButton = (Button) findViewById(R.id.home_button);
        homeButton.setOnClickListener(this);

    }

    // For when the user selects a reporting type from dropdown
    @Override
    public void onItemSelected(AdapterView<?> parent, View v, int position, long id) {
        // DOCS: https://developer.android.com/reference/android/widget/AdapterView.OnItemSelectedListener#onItemSelected(android.widget.AdapterView%3C?%3E,%20android.view.View,%20int,%20long)


        // Get the user's reporting type (app or study space/bathroom)
        String userChoice = parent.getItemAtPosition(position).toString();

        // Ensure that the user does not choose the placeholder text
        if (userChoice.equals("Choose an option")) {
            Toast.makeText(this, "Unsuccessful: Please select 'App' or 'Study Space or Bathroom'", Toast.LENGTH_SHORT).show();
        } else {
            Toast.makeText(this, "Selected: " + userChoice, Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {
        // This method is required if we implement OnItemSelectedListener
    }

    // For when the user presses the 'Next' Button or 'Back' Button
    public void onClick(View v) {

        // User pressed NEXT BUTTON
        if (v.getId() == R.id.next_button_report_feature) {
            Intent intent = new Intent(this, ReportingFilter.class);
            startActivity(intent);

            // User pressed BACK BUTTON
        } else if (v.getId() == R.id.back_button_report_feature) {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);

        // User pressed HOME BUTTON
        } else if (v.getId() == R.id.home_button) {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);
        }

    }
}